server.port: 8083

spring:
  application:
    name: product-catalog
  mongodb:
    uri: mongodb://root:algashop@localhost:27017/product_catalog?authSource=admin
#    representation.uuid: standard

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG
    org.mongodb.driver.connection: DEBUG
